FROM python:3.9-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY serve/predict.py /app/

# Install Flask and google-cloud-storage
RUN pip install Flask google-cloud-storage scikit-learn grpcio gcsfs  \
    python-dotenv

ENV AIP_STORAGE_URI=gs://us-east1-airflow-composer-05582c7e-bucket/model
ENV AIP_HEALTH_ROUTE=/ping
ENV AIP_PREDICT_ROUTE=/predict
ENV AIP_HTTP_PORT=8080
ENV BUCKET_NAME=us-east1-airflow-composer-05582c7e-bucket

ENV PROJECT_ID=wegf-mlops

# Run predict.py when the container launches
ENTRYPOINT ["python", "predict.py"]